/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Thu Nov 22 16:38:50 2018. */

#ifndef PB_PROTO_ATTRIBUTES_PB_H_INCLUDED
#define PB_PROTO_ATTRIBUTES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _proto_Attribute_ErrorCode {
    proto_Attribute_ErrorCode_UNKNOWN_ERROR = 0,
    proto_Attribute_ErrorCode_SECURITY_CODE_CANCELED = 300,
    proto_Attribute_ErrorCode_BAD_REQUEST = 400,
    proto_Attribute_ErrorCode_UNAUTHORIZED = 401,
    proto_Attribute_ErrorCode_SECURITY_CODE_ERROR = 402
} proto_Attribute_ErrorCode;
#define _proto_Attribute_ErrorCode_MIN proto_Attribute_ErrorCode_UNKNOWN_ERROR
#define _proto_Attribute_ErrorCode_MAX proto_Attribute_ErrorCode_SECURITY_CODE_ERROR
#define _proto_Attribute_ErrorCode_ARRAYSIZE ((proto_Attribute_ErrorCode)(proto_Attribute_ErrorCode_SECURITY_CODE_ERROR+1))

typedef enum _proto_Attribute_UnlockType {
    proto_Attribute_UnlockType_UNKNOWN = 0,
    proto_Attribute_UnlockType_BLUETOOTH_APP = 1,
    proto_Attribute_UnlockType_REMOTE_APP = 2,
    proto_Attribute_UnlockType_REMOTE_ADMINISTRATOR = 3,
    proto_Attribute_UnlockType_PHYSICAL_KEY = 4,
    proto_Attribute_UnlockType_PHYSICAL_IC_CARD = 5,
    proto_Attribute_UnlockType_PHYSICAL_RESIDENT_ID_CARD = 6
} proto_Attribute_UnlockType;
#define _proto_Attribute_UnlockType_MIN proto_Attribute_UnlockType_UNKNOWN
#define _proto_Attribute_UnlockType_MAX proto_Attribute_UnlockType_PHYSICAL_RESIDENT_ID_CARD
#define _proto_Attribute_UnlockType_ARRAYSIZE ((proto_Attribute_UnlockType)(proto_Attribute_UnlockType_PHYSICAL_RESIDENT_ID_CARD+1))

/* Struct definitions */
typedef struct _proto_Attribute {
    char dummy_field;
/* @@protoc_insertion_point(struct:proto_Attribute) */
} proto_Attribute;

typedef struct _proto_Authorization {
    int32_t encryption_algorithm;
    pb_callback_t key_encrypted;
    int64_t start_time;
    int64_t end_time;
    int64_t user_id;
/* @@protoc_insertion_point(struct:proto_Authorization) */
} proto_Authorization;

typedef struct _proto_BreakEvent {
    int64_t even_time;
/* @@protoc_insertion_point(struct:proto_BreakEvent) */
} proto_BreakEvent;

typedef struct _proto_ErrorCode {
    proto_Attribute_ErrorCode error_code;
    pb_callback_t error_message;
/* @@protoc_insertion_point(struct:proto_ErrorCode) */
} proto_ErrorCode;

typedef struct _proto_SecurityCode {
    int32_t encryption_algorithm;
    pb_callback_t security_code;
/* @@protoc_insertion_point(struct:proto_SecurityCode) */
} proto_SecurityCode;

typedef struct _proto_Unlock {
    proto_Attribute_UnlockType unlock_type;
    int64_t user_id;
/* @@protoc_insertion_point(struct:proto_Unlock) */
} proto_Unlock;

typedef struct _proto_UnlockEvent {
    int64_t even_time;
    proto_Attribute_UnlockType unlock_type;
    int32_t unlock_result;
    int64_t user_id;
/* @@protoc_insertion_point(struct:proto_UnlockEvent) */
} proto_UnlockEvent;

typedef struct _proto_VoiceSwitch {
    bool enable;
/* @@protoc_insertion_point(struct:proto_VoiceSwitch) */
} proto_VoiceSwitch;

/* Default values for struct fields */

/* Initializer values for message structs */
#define proto_Attribute_init_default             {0}
#define proto_ErrorCode_init_default             {_proto_Attribute_ErrorCode_MIN, {{NULL}, NULL}}
#define proto_SecurityCode_init_default          {0, {{NULL}, NULL}}
#define proto_Authorization_init_default         {0, {{NULL}, NULL}, 0, 0, 0}
#define proto_Unlock_init_default                {_proto_Attribute_UnlockType_MIN, 0}
#define proto_UnlockEvent_init_default           {0, _proto_Attribute_UnlockType_MIN, 0, 0}
#define proto_BreakEvent_init_default            {0}
#define proto_VoiceSwitch_init_default           {0}
#define proto_Attribute_init_zero                {0}
#define proto_ErrorCode_init_zero                {_proto_Attribute_ErrorCode_MIN, {{NULL}, NULL}}
#define proto_SecurityCode_init_zero             {0, {{NULL}, NULL}}
#define proto_Authorization_init_zero            {0, {{NULL}, NULL}, 0, 0, 0}
#define proto_Unlock_init_zero                   {_proto_Attribute_UnlockType_MIN, 0}
#define proto_UnlockEvent_init_zero              {0, _proto_Attribute_UnlockType_MIN, 0, 0}
#define proto_BreakEvent_init_zero               {0}
#define proto_VoiceSwitch_init_zero              {0}

/* Field tags (for use in manual encoding/decoding) */
#define proto_Authorization_encryption_algorithm_tag 1
#define proto_Authorization_key_encrypted_tag    2
#define proto_Authorization_start_time_tag       3
#define proto_Authorization_end_time_tag         4
#define proto_Authorization_user_id_tag          5
#define proto_BreakEvent_even_time_tag           1
#define proto_ErrorCode_error_code_tag           1
#define proto_ErrorCode_error_message_tag        2
#define proto_SecurityCode_encryption_algorithm_tag 1
#define proto_SecurityCode_security_code_tag     2
#define proto_Unlock_unlock_type_tag             1
#define proto_Unlock_user_id_tag                 2
#define proto_UnlockEvent_even_time_tag          1
#define proto_UnlockEvent_unlock_type_tag        2
#define proto_UnlockEvent_unlock_result_tag      3
#define proto_UnlockEvent_user_id_tag            4
#define proto_VoiceSwitch_enable_tag             1

/* Struct field encoding specification for nanopb */
extern const pb_field_t proto_Attribute_fields[1];
extern const pb_field_t proto_ErrorCode_fields[3];
extern const pb_field_t proto_SecurityCode_fields[3];
extern const pb_field_t proto_Authorization_fields[6];
extern const pb_field_t proto_Unlock_fields[3];
extern const pb_field_t proto_UnlockEvent_fields[5];
extern const pb_field_t proto_BreakEvent_fields[2];
extern const pb_field_t proto_VoiceSwitch_fields[2];

/* Maximum encoded size of messages (where known) */
#define proto_Attribute_size                     0
/* proto_ErrorCode_size depends on runtime parameters */
/* proto_SecurityCode_size depends on runtime parameters */
/* proto_Authorization_size depends on runtime parameters */
#define proto_Unlock_size                        13
#define proto_UnlockEvent_size                   35
#define proto_BreakEvent_size                    11
#define proto_VoiceSwitch_size                   2

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ATTRIBUTES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
