/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Thu Nov 22 16:38:50 2018. */

#include "Attributes.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t proto_Attribute_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t proto_ErrorCode_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, proto_ErrorCode, error_code, error_code, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, proto_ErrorCode, error_message, error_code, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_SecurityCode_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, proto_SecurityCode, encryption_algorithm, encryption_algorithm, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, proto_SecurityCode, security_code, encryption_algorithm, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Authorization_fields[6] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, proto_Authorization, encryption_algorithm, encryption_algorithm, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, proto_Authorization, key_encrypted, encryption_algorithm, 0),
    PB_FIELD(  3, INT64   , SINGULAR, STATIC  , OTHER, proto_Authorization, start_time, key_encrypted, 0),
    PB_FIELD(  4, INT64   , SINGULAR, STATIC  , OTHER, proto_Authorization, end_time, start_time, 0),
    PB_FIELD(  5, INT64   , SINGULAR, STATIC  , OTHER, proto_Authorization, user_id, end_time, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_Unlock_fields[3] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, proto_Unlock, unlock_type, unlock_type, 0),
    PB_FIELD(  2, INT64   , SINGULAR, STATIC  , OTHER, proto_Unlock, user_id, unlock_type, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_UnlockEvent_fields[5] = {
    PB_FIELD(  1, INT64   , SINGULAR, STATIC  , FIRST, proto_UnlockEvent, even_time, even_time, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, proto_UnlockEvent, unlock_type, even_time, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, proto_UnlockEvent, unlock_result, unlock_type, 0),
    PB_FIELD(  4, INT64   , SINGULAR, STATIC  , OTHER, proto_UnlockEvent, user_id, unlock_result, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_BreakEvent_fields[2] = {
    PB_FIELD(  1, INT64   , SINGULAR, STATIC  , FIRST, proto_BreakEvent, even_time, even_time, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_VoiceSwitch_fields[2] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, proto_VoiceSwitch, enable, enable, 0),
    PB_LAST_FIELD
};




/* @@protoc_insertion_point(eof) */
