/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Thu Nov 22 16:38:46 2018. */

#include "Messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t proto_DeviceRegisterRequest_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_DeviceRegisterRequest, lock_no, lock_no, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, proto_DeviceRegisterRequest, security_code, lock_no, &proto_SecurityCode_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_DeviceRegisterResponse_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_DeviceRegisterResponse, lock_no, lock_no, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, proto_DeviceRegisterResponse, successful, lock_no, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, proto_DeviceRegisterResponse, error_code, successful, &proto_ErrorCode_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, proto_DeviceRegisterResponse, security_code, error_code, &proto_SecurityCode_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_MessageNumberQueryRequest_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_MessageNumberQueryRequest, lock_no, lock_no, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_MessageNumberQueryResponse_fields[5] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_MessageNumberQueryResponse, lock_no, lock_no, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, proto_MessageNumberQueryResponse, successful, lock_no, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, proto_MessageNumberQueryResponse, error_code, successful, &proto_ErrorCode_fields),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, proto_MessageNumberQueryResponse, message_number, error_code, 0),
    PB_LAST_FIELD
};

const pb_field_t proto_AuthorizationSendRequest_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_AuthorizationSendRequest, lock_no, lock_no, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, proto_AuthorizationSendRequest, authorization, lock_no, &proto_Authorization_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_AuthorizationSendResponse_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_AuthorizationSendResponse, lock_no, lock_no, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, proto_AuthorizationSendResponse, successful, lock_no, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, proto_AuthorizationSendResponse, error_code, successful, &proto_ErrorCode_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_RemoteUnLockRequest_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_RemoteUnLockRequest, lock_no, lock_no, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, proto_RemoteUnLockRequest, unlock, lock_no, &proto_Unlock_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_RemoteUnLockResponse_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_RemoteUnLockResponse, lock_no, lock_no, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, proto_RemoteUnLockResponse, successful, lock_no, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, proto_RemoteUnLockResponse, error_code, successful, &proto_ErrorCode_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_EventReportRequest_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_EventReportRequest, lock_no, lock_no, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, proto_EventReportRequest, unlock_event, lock_no, &proto_UnlockEvent_fields),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, proto_EventReportRequest, break_event, unlock_event, &proto_BreakEvent_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_EventReportResponse_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_EventReportResponse, lock_no, lock_no, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, proto_EventReportResponse, successful, lock_no, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, proto_EventReportResponse, error_code, successful, &proto_ErrorCode_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_DeviceSetSendRequest_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_DeviceSetSendRequest, lock_no, lock_no, 0),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, proto_DeviceSetSendRequest, voice_set, lock_no, &proto_VoiceSwitch_fields),
    PB_LAST_FIELD
};

const pb_field_t proto_DeviceSetSendResponse_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, proto_DeviceSetSendResponse, lock_no, lock_no, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, proto_DeviceSetSendResponse, successful, lock_no, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, proto_DeviceSetSendResponse, error_code, successful, &proto_ErrorCode_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_DeviceRegisterRequest, security_code) < 65536 && pb_membersize(proto_DeviceRegisterResponse, security_code) < 65536 && pb_membersize(proto_RemoteUnLockRequest, unlock) < 65536 && pb_membersize(proto_DeviceSetSendRequest, voice_set) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_proto_DeviceRegisterRequest_proto_DeviceRegisterResponse_proto_MessageNumberQueryRequest_proto_MessageNumberQueryResponse_proto_AuthorizationSendRequest_proto_AuthorizationSendResponse_proto_RemoteUnLockRequest_proto_RemoteUnLockResponse_proto_EventReportRequest_proto_EventReportResponse_proto_DeviceSetSendRequest_proto_DeviceSetSendResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_DeviceRegisterRequest, security_code) < 256 && pb_membersize(proto_DeviceRegisterResponse, security_code) < 256 && pb_membersize(proto_RemoteUnLockRequest, unlock) < 256 && pb_membersize(proto_DeviceSetSendRequest, voice_set) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_proto_DeviceRegisterRequest_proto_DeviceRegisterResponse_proto_MessageNumberQueryRequest_proto_MessageNumberQueryResponse_proto_AuthorizationSendRequest_proto_AuthorizationSendResponse_proto_RemoteUnLockRequest_proto_RemoteUnLockResponse_proto_EventReportRequest_proto_EventReportResponse_proto_DeviceSetSendRequest_proto_DeviceSetSendResponse)
#endif


/* @@protoc_insertion_point(eof) */
