/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Thu Nov 22 16:38:46 2018. */

#ifndef PB_PROTO_MESSAGES_PB_H_INCLUDED
#define PB_PROTO_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#include "Attributes.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _proto_AuthorizationSendRequest {
    pb_callback_t lock_no;
    pb_callback_t authorization;
/* @@protoc_insertion_point(struct:proto_AuthorizationSendRequest) */
} proto_AuthorizationSendRequest;

typedef struct _proto_EventReportRequest {
    pb_callback_t lock_no;
    pb_callback_t unlock_event;
    pb_callback_t break_event;
/* @@protoc_insertion_point(struct:proto_EventReportRequest) */
} proto_EventReportRequest;

typedef struct _proto_MessageNumberQueryRequest {
    pb_callback_t lock_no;
/* @@protoc_insertion_point(struct:proto_MessageNumberQueryRequest) */
} proto_MessageNumberQueryRequest;

typedef struct _proto_AuthorizationSendResponse {
    pb_callback_t lock_no;
    bool successful;
    pb_callback_t error_code;
/* @@protoc_insertion_point(struct:proto_AuthorizationSendResponse) */
} proto_AuthorizationSendResponse;

typedef struct _proto_DeviceRegisterRequest {
    pb_callback_t lock_no;
    proto_SecurityCode security_code;
/* @@protoc_insertion_point(struct:proto_DeviceRegisterRequest) */
} proto_DeviceRegisterRequest;

typedef struct _proto_DeviceRegisterResponse {
    pb_callback_t lock_no;
    bool successful;
    pb_callback_t error_code;
    proto_SecurityCode security_code;
/* @@protoc_insertion_point(struct:proto_DeviceRegisterResponse) */
} proto_DeviceRegisterResponse;

typedef struct _proto_DeviceSetSendRequest {
    pb_callback_t lock_no;
    proto_VoiceSwitch voice_set;
/* @@protoc_insertion_point(struct:proto_DeviceSetSendRequest) */
} proto_DeviceSetSendRequest;

typedef struct _proto_DeviceSetSendResponse {
    pb_callback_t lock_no;
    bool successful;
    pb_callback_t error_code;
/* @@protoc_insertion_point(struct:proto_DeviceSetSendResponse) */
} proto_DeviceSetSendResponse;

typedef struct _proto_EventReportResponse {
    pb_callback_t lock_no;
    bool successful;
    pb_callback_t error_code;
/* @@protoc_insertion_point(struct:proto_EventReportResponse) */
} proto_EventReportResponse;

typedef struct _proto_MessageNumberQueryResponse {
    pb_callback_t lock_no;
    bool successful;
    pb_callback_t error_code;
    uint32_t message_number;
/* @@protoc_insertion_point(struct:proto_MessageNumberQueryResponse) */
} proto_MessageNumberQueryResponse;

typedef struct _proto_RemoteUnLockRequest {
    pb_callback_t lock_no;
    proto_Unlock unlock;
/* @@protoc_insertion_point(struct:proto_RemoteUnLockRequest) */
} proto_RemoteUnLockRequest;

typedef struct _proto_RemoteUnLockResponse {
    pb_callback_t lock_no;
    bool successful;
    pb_callback_t error_code;
/* @@protoc_insertion_point(struct:proto_RemoteUnLockResponse) */
} proto_RemoteUnLockResponse;

/* Default values for struct fields */

/* Initializer values for message structs */
#define proto_DeviceRegisterRequest_init_default {{{NULL}, NULL}, proto_SecurityCode_init_default}
#define proto_DeviceRegisterResponse_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}, proto_SecurityCode_init_default}
#define proto_MessageNumberQueryRequest_init_default {{{NULL}, NULL}}
#define proto_MessageNumberQueryResponse_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define proto_AuthorizationSendRequest_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define proto_AuthorizationSendResponse_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define proto_RemoteUnLockRequest_init_default   {{{NULL}, NULL}, proto_Unlock_init_default}
#define proto_RemoteUnLockResponse_init_default  {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define proto_EventReportRequest_init_default    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define proto_EventReportResponse_init_default   {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define proto_DeviceSetSendRequest_init_default  {{{NULL}, NULL}, proto_VoiceSwitch_init_default}
#define proto_DeviceSetSendResponse_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define proto_DeviceRegisterRequest_init_zero    {{{NULL}, NULL}, proto_SecurityCode_init_zero}
#define proto_DeviceRegisterResponse_init_zero   {{{NULL}, NULL}, 0, {{NULL}, NULL}, proto_SecurityCode_init_zero}
#define proto_MessageNumberQueryRequest_init_zero {{{NULL}, NULL}}
#define proto_MessageNumberQueryResponse_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define proto_AuthorizationSendRequest_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define proto_AuthorizationSendResponse_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define proto_RemoteUnLockRequest_init_zero      {{{NULL}, NULL}, proto_Unlock_init_zero}
#define proto_RemoteUnLockResponse_init_zero     {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define proto_EventReportRequest_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define proto_EventReportResponse_init_zero      {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define proto_DeviceSetSendRequest_init_zero     {{{NULL}, NULL}, proto_VoiceSwitch_init_zero}
#define proto_DeviceSetSendResponse_init_zero    {{{NULL}, NULL}, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define proto_AuthorizationSendRequest_lock_no_tag 1
#define proto_AuthorizationSendRequest_authorization_tag 2
#define proto_EventReportRequest_lock_no_tag     1
#define proto_EventReportRequest_unlock_event_tag 2
#define proto_EventReportRequest_break_event_tag 3
#define proto_MessageNumberQueryRequest_lock_no_tag 1
#define proto_AuthorizationSendResponse_lock_no_tag 1
#define proto_AuthorizationSendResponse_successful_tag 2
#define proto_AuthorizationSendResponse_error_code_tag 3
#define proto_DeviceRegisterRequest_lock_no_tag  1
#define proto_DeviceRegisterRequest_security_code_tag 2
#define proto_DeviceRegisterResponse_lock_no_tag 1
#define proto_DeviceRegisterResponse_successful_tag 2
#define proto_DeviceRegisterResponse_error_code_tag 3
#define proto_DeviceRegisterResponse_security_code_tag 4
#define proto_DeviceSetSendRequest_lock_no_tag   1
#define proto_DeviceSetSendRequest_voice_set_tag 2
#define proto_DeviceSetSendResponse_lock_no_tag  1
#define proto_DeviceSetSendResponse_successful_tag 2
#define proto_DeviceSetSendResponse_error_code_tag 3
#define proto_EventReportResponse_lock_no_tag    1
#define proto_EventReportResponse_successful_tag 2
#define proto_EventReportResponse_error_code_tag 3
#define proto_MessageNumberQueryResponse_lock_no_tag 1
#define proto_MessageNumberQueryResponse_successful_tag 2
#define proto_MessageNumberQueryResponse_error_code_tag 3
#define proto_MessageNumberQueryResponse_message_number_tag 4
#define proto_RemoteUnLockRequest_lock_no_tag    1
#define proto_RemoteUnLockRequest_unlock_tag     2
#define proto_RemoteUnLockResponse_lock_no_tag   1
#define proto_RemoteUnLockResponse_successful_tag 2
#define proto_RemoteUnLockResponse_error_code_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t proto_DeviceRegisterRequest_fields[3];
extern const pb_field_t proto_DeviceRegisterResponse_fields[5];
extern const pb_field_t proto_MessageNumberQueryRequest_fields[2];
extern const pb_field_t proto_MessageNumberQueryResponse_fields[5];
extern const pb_field_t proto_AuthorizationSendRequest_fields[3];
extern const pb_field_t proto_AuthorizationSendResponse_fields[4];
extern const pb_field_t proto_RemoteUnLockRequest_fields[3];
extern const pb_field_t proto_RemoteUnLockResponse_fields[4];
extern const pb_field_t proto_EventReportRequest_fields[4];
extern const pb_field_t proto_EventReportResponse_fields[4];
extern const pb_field_t proto_DeviceSetSendRequest_fields[3];
extern const pb_field_t proto_DeviceSetSendResponse_fields[4];

/* Maximum encoded size of messages (where known) */
/* proto_DeviceRegisterRequest_size depends on runtime parameters */
/* proto_DeviceRegisterResponse_size depends on runtime parameters */
/* proto_MessageNumberQueryRequest_size depends on runtime parameters */
/* proto_MessageNumberQueryResponse_size depends on runtime parameters */
/* proto_AuthorizationSendRequest_size depends on runtime parameters */
/* proto_AuthorizationSendResponse_size depends on runtime parameters */
/* proto_RemoteUnLockRequest_size depends on runtime parameters */
/* proto_RemoteUnLockResponse_size depends on runtime parameters */
/* proto_EventReportRequest_size depends on runtime parameters */
/* proto_EventReportResponse_size depends on runtime parameters */
/* proto_DeviceSetSendRequest_size depends on runtime parameters */
/* proto_DeviceSetSendResponse_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
