/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Thu Nov 22 16:37:58 2018. */

#include "MessagesDescriptor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t proto_SelfDescribingMessage_fields[16] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, proto_SelfDescribingMessage, protocol_method, protocol_method, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, proto_SelfDescribingMessage, message_method, protocol_method, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, proto_SelfDescribingMessage, transaction_id, message_method, 0),
    PB_ONEOF_FIELD(message,   4, MESSAGE , ONEOF, STATIC  , OTHER, proto_SelfDescribingMessage, deviceRegisterRequest, transaction_id, &proto_DeviceRegisterRequest_fields),
    PB_ONEOF_FIELD(message,   5, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, deviceRegisterResponse, transaction_id, &proto_DeviceRegisterResponse_fields),
    PB_ONEOF_FIELD(message,   6, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, messageNumberQueryRequest, transaction_id, &proto_MessageNumberQueryRequest_fields),
    PB_ONEOF_FIELD(message,   7, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, messageNumberQueryResponse, transaction_id, &proto_MessageNumberQueryResponse_fields),
    PB_ONEOF_FIELD(message,   8, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, authorizationSendRequest, transaction_id, &proto_AuthorizationSendRequest_fields),
    PB_ONEOF_FIELD(message,   9, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, authorizationSendResponse, transaction_id, &proto_AuthorizationSendResponse_fields),
    PB_ONEOF_FIELD(message,  10, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, remoteUnLockRequest, transaction_id, &proto_RemoteUnLockRequest_fields),
    PB_ONEOF_FIELD(message,  11, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, remoteUnLockResponse, transaction_id, &proto_RemoteUnLockResponse_fields),
    PB_ONEOF_FIELD(message,  12, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, eventReportRequest, transaction_id, &proto_EventReportRequest_fields),
    PB_ONEOF_FIELD(message,  13, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, eventReportResponse, transaction_id, &proto_EventReportResponse_fields),
    PB_ONEOF_FIELD(message,  14, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, deviceSetSendRequest, transaction_id, &proto_DeviceSetSendRequest_fields),
    PB_ONEOF_FIELD(message,  15, MESSAGE , ONEOF, STATIC  , UNION, proto_SelfDescribingMessage, deviceSetSendResponse, transaction_id, &proto_DeviceSetSendResponse_fields),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_SelfDescribingMessage, message.deviceRegisterRequest) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.deviceRegisterResponse) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.messageNumberQueryRequest) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.messageNumberQueryResponse) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.authorizationSendRequest) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.authorizationSendResponse) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.remoteUnLockRequest) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.remoteUnLockResponse) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.eventReportRequest) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.eventReportResponse) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.deviceSetSendRequest) < 65536 && pb_membersize(proto_SelfDescribingMessage, message.deviceSetSendResponse) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_proto_SelfDescribingMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(proto_SelfDescribingMessage, message.deviceRegisterRequest) < 256 && pb_membersize(proto_SelfDescribingMessage, message.deviceRegisterResponse) < 256 && pb_membersize(proto_SelfDescribingMessage, message.messageNumberQueryRequest) < 256 && pb_membersize(proto_SelfDescribingMessage, message.messageNumberQueryResponse) < 256 && pb_membersize(proto_SelfDescribingMessage, message.authorizationSendRequest) < 256 && pb_membersize(proto_SelfDescribingMessage, message.authorizationSendResponse) < 256 && pb_membersize(proto_SelfDescribingMessage, message.remoteUnLockRequest) < 256 && pb_membersize(proto_SelfDescribingMessage, message.remoteUnLockResponse) < 256 && pb_membersize(proto_SelfDescribingMessage, message.eventReportRequest) < 256 && pb_membersize(proto_SelfDescribingMessage, message.eventReportResponse) < 256 && pb_membersize(proto_SelfDescribingMessage, message.deviceSetSendRequest) < 256 && pb_membersize(proto_SelfDescribingMessage, message.deviceSetSendResponse) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_proto_SelfDescribingMessage)
#endif


/* @@protoc_insertion_point(eof) */
