/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Thu Nov 22 16:37:58 2018. */

#ifndef PB_PROTO_MESSAGESDESCRIPTOR_PB_H_INCLUDED
#define PB_PROTO_MESSAGESDESCRIPTOR_PB_H_INCLUDED
#include <pb.h>

#include "Messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _proto_SelfDescribingMessage_ProtocolMethod {
    proto_SelfDescribingMessage_ProtocolMethod_Request = 0,
    proto_SelfDescribingMessage_ProtocolMethod_Response = 1
} proto_SelfDescribingMessage_ProtocolMethod;
#define _proto_SelfDescribingMessage_ProtocolMethod_MIN proto_SelfDescribingMessage_ProtocolMethod_Request
#define _proto_SelfDescribingMessage_ProtocolMethod_MAX proto_SelfDescribingMessage_ProtocolMethod_Response
#define _proto_SelfDescribingMessage_ProtocolMethod_ARRAYSIZE ((proto_SelfDescribingMessage_ProtocolMethod)(proto_SelfDescribingMessage_ProtocolMethod_Response+1))

typedef enum _proto_SelfDescribingMessage_MessageMethod {
    proto_SelfDescribingMessage_MessageMethod_DeviceRegister = 0,
    proto_SelfDescribingMessage_MessageMethod_MessageNumberQuery = 1,
    proto_SelfDescribingMessage_MessageMethod_AuthorizationSend = 2,
    proto_SelfDescribingMessage_MessageMethod_RemoteUnLock = 3,
    proto_SelfDescribingMessage_MessageMethod_EventReport = 4,
    proto_SelfDescribingMessage_MessageMethod_DeviceSetSend = 5
} proto_SelfDescribingMessage_MessageMethod;
#define _proto_SelfDescribingMessage_MessageMethod_MIN proto_SelfDescribingMessage_MessageMethod_DeviceRegister
#define _proto_SelfDescribingMessage_MessageMethod_MAX proto_SelfDescribingMessage_MessageMethod_DeviceSetSend
#define _proto_SelfDescribingMessage_MessageMethod_ARRAYSIZE ((proto_SelfDescribingMessage_MessageMethod)(proto_SelfDescribingMessage_MessageMethod_DeviceSetSend+1))

/* Struct definitions */
typedef struct _proto_SelfDescribingMessage {
    proto_SelfDescribingMessage_ProtocolMethod protocol_method;
    proto_SelfDescribingMessage_MessageMethod message_method;
    int32_t transaction_id;
    pb_size_t which_message;
    union {
        proto_DeviceRegisterRequest deviceRegisterRequest;
        proto_DeviceRegisterResponse deviceRegisterResponse;
        proto_MessageNumberQueryRequest messageNumberQueryRequest;
        proto_MessageNumberQueryResponse messageNumberQueryResponse;
        proto_AuthorizationSendRequest authorizationSendRequest;
        proto_AuthorizationSendResponse authorizationSendResponse;
        proto_RemoteUnLockRequest remoteUnLockRequest;
        proto_RemoteUnLockResponse remoteUnLockResponse;
        proto_EventReportRequest eventReportRequest;
        proto_EventReportResponse eventReportResponse;
        proto_DeviceSetSendRequest deviceSetSendRequest;
        proto_DeviceSetSendResponse deviceSetSendResponse;
    } message;
/* @@protoc_insertion_point(struct:proto_SelfDescribingMessage) */
} proto_SelfDescribingMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define proto_SelfDescribingMessage_init_default {_proto_SelfDescribingMessage_ProtocolMethod_MIN, _proto_SelfDescribingMessage_MessageMethod_MIN, 0, 0, {proto_DeviceRegisterRequest_init_default}}
#define proto_SelfDescribingMessage_init_zero    {_proto_SelfDescribingMessage_ProtocolMethod_MIN, _proto_SelfDescribingMessage_MessageMethod_MIN, 0, 0, {proto_DeviceRegisterRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define proto_SelfDescribingMessage_deviceRegisterRequest_tag 4
#define proto_SelfDescribingMessage_deviceRegisterResponse_tag 5
#define proto_SelfDescribingMessage_messageNumberQueryRequest_tag 6
#define proto_SelfDescribingMessage_messageNumberQueryResponse_tag 7
#define proto_SelfDescribingMessage_authorizationSendRequest_tag 8
#define proto_SelfDescribingMessage_authorizationSendResponse_tag 9
#define proto_SelfDescribingMessage_remoteUnLockRequest_tag 10
#define proto_SelfDescribingMessage_remoteUnLockResponse_tag 11
#define proto_SelfDescribingMessage_eventReportRequest_tag 12
#define proto_SelfDescribingMessage_eventReportResponse_tag 13
#define proto_SelfDescribingMessage_deviceSetSendRequest_tag 14
#define proto_SelfDescribingMessage_deviceSetSendResponse_tag 15
#define proto_SelfDescribingMessage_protocol_method_tag 1
#define proto_SelfDescribingMessage_message_method_tag 2
#define proto_SelfDescribingMessage_transaction_id_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t proto_SelfDescribingMessage_fields[16];

/* Maximum encoded size of messages (where known) */
#define proto_SelfDescribingMessage_size         (20 + sizeof(union{char f4[proto_DeviceRegisterRequest_size]; char f5[proto_DeviceRegisterResponse_size]; char f6[proto_MessageNumberQueryRequest_size]; char f7[proto_MessageNumberQueryResponse_size]; char f8[proto_AuthorizationSendRequest_size]; char f9[proto_AuthorizationSendResponse_size]; char f10[proto_RemoteUnLockRequest_size]; char f11[proto_RemoteUnLockResponse_size]; char f12[proto_EventReportRequest_size]; char f13[proto_EventReportResponse_size]; char f14[proto_DeviceSetSendRequest_size]; char f15[proto_DeviceSetSendResponse_size];}))

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGESDESCRIPTOR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
